
package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alertTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="alertTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="RESCHEDULEFAILURES"/&gt;
 *     &lt;enumeration value="SUSPENDEDJOBS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "alertTypeType")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.5", date = "2023-05-09T15:46:53+01:00")
public enum AlertTypeType {

    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),
    RESCHEDULEFAILURES("RESCHEDULEFAILURES"),
    SUSPENDEDJOBS("SUSPENDEDJOBS");
    private final String value;

    AlertTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlertTypeType fromValue(String v) {
        for (AlertTypeType c: AlertTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
