
package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for availableValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="availableValue"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="NO"/&gt;
 *     &lt;enumeration value="YES"/&gt;
 *     &lt;enumeration value="MAYBE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "availableValue")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.5", date = "2023-05-09T15:46:53+01:00")
public enum AvailableValue {

    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),
    NO("NO"),
    YES("YES"),
    MAYBE("MAYBE");
    private final String value;

    AvailableValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AvailableValue fromValue(String v) {
        for (AvailableValue c: AvailableValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
