
package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookingResourceLock.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="bookingResourceLock"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="lockAsSpecified"/&gt;
 *     &lt;enumeration value="lockAfterSchedule"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "bookingResourceLock")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.5", date = "2023-05-09T15:46:53+01:00")
public enum BookingResourceLock {

    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),
    @XmlEnumValue("lockAsSpecified")
    LOCK_AS_SPECIFIED("lockAsSpecified"),
    @XmlEnumValue("lockAfterSchedule")
    LOCK_AFTER_SCHEDULE("lockAfterSchedule");
    private final String value;

    BookingResourceLock(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BookingResourceLock fromValue(String v) {
        for (BookingResourceLock c: BookingResourceLock.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
