
package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity")
@XmlSeeAlso({
    Ability.class,
    Alert.class,
    AvailableDay.class,
    AvailablePeriod.class,
    Booking.class,
    BookingCode.class,
    BookingCodeDefinition.class,
    BusinessData.class,
    BusinessDataDefinition.class,
    DaySlotsInfo.class,
    Location.class,
    LocationLine.class,
    Order.class,
    OrderPattern.class,
    Resource.class,
    ResourceTemplate.class,
    Sector.class,
    SlotInfo.class,
    Unavailability.class,
    UnavailabilityReason.class,
    Command.class,
    CommandResponse.class,
    WorkingHour.class
})
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.5", date = "2023-05-09T15:46:53+01:00")
public class Entity {


}
