package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-09T15:46:53.720+01:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "SOAP")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00", comments = "Apache CXF 3.5.5")
public interface SOAP {

    @WebMethod
    @RequestWrapper(localName = "getSchedule", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.GetSchedule")
    @ResponseWrapper(localName = "getScheduleResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.GetScheduleResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbGetScheduleResponse getSchedule(

        @WebParam(name = "getSchedule", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbGetSchedule getSchedule
    );

    @WebMethod
    @RequestWrapper(localName = "deleteBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.DeleteBooking")
    @ResponseWrapper(localName = "deleteBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.DeleteBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbDeleteBookingResponse deleteBooking(

        @WebParam(name = "deleteBooking", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbDeleteBooking deleteBooking
    );

    @WebMethod
    @RequestWrapper(localName = "selectMetaData", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectMetaData")
    @ResponseWrapper(localName = "selectMetaDataResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectMetaDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbSelectMetaDataResponse selectMetaData(

        @WebParam(name = "selectMetaData", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbSelectMetaData selectMetaData
    );

    @WebMethod
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateOrder")
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateOrderResponse updateOrder(

        @WebParam(name = "updateOrder", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateOrder updateOrder
    );

    @WebMethod(action = "http://localhost:8080/checkAvailability")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CheckAvailabilityResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCheckAvailabilityResponse checkAvailability(

        @WebParam(name = "checkAvailability", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCheckAvailability checkAvailability
    );

    @WebMethod
    @RequestWrapper(localName = "selectAlerts", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectAlerts")
    @ResponseWrapper(localName = "selectAlertsResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectAlertsResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbSelectAlertsResponse selectAlerts(

        @WebParam(name = "selectAlerts", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbSelectAlerts selectAlerts
    );

    @WebMethod
    @RequestWrapper(localName = "selectResource", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectResource")
    @ResponseWrapper(localName = "selectResourceResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectResourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbSelectResourceResponse selectResource(

        @WebParam(name = "selectResource", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbSelectResource selectResource
    );

    @WebMethod
    @RequestWrapper(localName = "createReservation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateReservation")
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateReservationResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCreateReservationResponse createReservation(

        @WebParam(name = "createReservation", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCreateReservation createReservation
    );

    @WebMethod
    @RequestWrapper(localName = "selectOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectOrder")
    @ResponseWrapper(localName = "selectOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbSelectOrderResponse selectOrder(

        @WebParam(name = "selectOrder", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbSelectOrder selectOrder
    );

    @WebMethod
    @RequestWrapper(localName = "selectBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectBooking")
    @ResponseWrapper(localName = "selectBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.SelectBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbSelectBookingResponse selectBooking(

        @WebParam(name = "selectBooking", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbSelectBooking selectBooking
    );

    @WebMethod
    @RequestWrapper(localName = "updateBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateBooking")
    @ResponseWrapper(localName = "updateBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateBookingResponse updateBooking(

        @WebParam(name = "updateBooking", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateBooking updateBooking
    );

    @WebMethod
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCreateOrderResponse createOrder(

        @WebParam(name = "createOrder", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCreateOrder createOrder
    );

    @WebMethod
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.DeleteOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbDeleteOrderResponse deleteOrder(

        @WebParam(name = "deleteOrder", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbDeleteOrder deleteOrder
    );

    @WebMethod
    @RequestWrapper(localName = "updateResource", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateResource")
    @ResponseWrapper(localName = "updateResourceResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateResourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateResourceResponse updateResource(

        @WebParam(name = "updateResource", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateResource updateResource
    );

    @WebMethod
    @RequestWrapper(localName = "createBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateBooking")
    @ResponseWrapper(localName = "createBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CreateBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCreateBookingResponse createBooking(

        @WebParam(name = "createBooking", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCreateBooking createBooking
    );

    @WebMethod
    @RequestWrapper(localName = "openSession", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.OpenSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbOpenSessionResponse openSession(

        @WebParam(name = "openSession", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbOpenSession openSession
    );

    @WebMethod
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CloseSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCloseSessionResponse closeSession(

        @WebParam(name = "closeSession", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCloseSession closeSession
    );

    @WebMethod
    @RequestWrapper(localName = "scheduleBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.ScheduleBooking")
    @ResponseWrapper(localName = "scheduleBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.ScheduleBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbScheduleBookingResponse scheduleBooking(

        @WebParam(name = "scheduleBooking", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbScheduleBooking scheduleBooking
    );

    @WebMethod
    @RequestWrapper(localName = "completeOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CompleteOrder")
    @ResponseWrapper(localName = "completeOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.CompleteOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbCompleteOrderResponse completeOrder(

        @WebParam(name = "completeOrder", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbCompleteOrder completeOrder
    );

    @WebMethod
    @RequestWrapper(localName = "confirmReservation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.ConfirmReservation")
    @ResponseWrapper(localName = "confirmReservationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.ConfirmReservationResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbConfirmReservationResponse confirmReservation(

        @WebParam(name = "confirmReservation", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbConfirmReservation confirmReservation
    );

    @WebMethod
    @RequestWrapper(localName = "updateBookingCode", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateBookingCode")
    @ResponseWrapper(localName = "updateBookingCodeResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateBookingCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateBookingCodeResponse updateBookingCode(

        @WebParam(name = "updateBookingCode", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateBookingCode updateBookingCode
    );

    @WebMethod
    @RequestWrapper(localName = "updateLocation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateLocation")
    @ResponseWrapper(localName = "updateLocationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "com.xmbrace.otwebserviceapi.autogenerated.UpdateLocationResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-05-09T15:46:53.720+01:00")
    public com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateLocationResponse updateLocation(

        @WebParam(name = "updateLocation", targetNamespace = "")
        com.xmbrace.otwebserviceapi.autogenerated.XmbUpdateLocation updateLocation
    );
}
