
package com.xmbrace.otwebserviceapi.autogenerated;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeOfList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="typeOfList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="notaList"/&gt;
 *     &lt;enumeration value="closedList"/&gt;
 *     &lt;enumeration value="openList"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeOfList")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.5", date = "2023-05-09T15:46:53+01:00")
public enum TypeOfList {

    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),
    @XmlEnumValue("notaList")
    NOTA_LIST("notaList"),
    @XmlEnumValue("closedList")
    CLOSED_LIST("closedList"),
    @XmlEnumValue("openList")
    OPEN_LIST("openList");
    private final String value;

    TypeOfList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfList fromValue(String v) {
        for (TypeOfList c: TypeOfList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
